M48
; DRILL file {KiCad 9.0.5} date 2026-02-06T18:32:03+1300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-06T18:32:03+13:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.850
%
G90
G05
T1
X131.11Y-62.68
X136.89Y-62.68
T2
X159.0Y-59.25
X162.0Y-59.25
M30
